### ISSUE TITLE
int 类型的经纬度怎么转换带小数的经纬度呢

### ISSUE THREAD

**Issue by 491134648** [SmallChi/JT808#16]
看JT808协议，GPS都是int整形的，怎么转常用的gps类型(包含小数点的)

**Comment by SmallChi** [comment]
大兄弟，你要认真看下协议才行，除以10^6次方，保留6位小数据。

**Comment by 491134648** [comment]
好的，谢谢！

**Comment by 491134648** [comment]
这种坐标中国境内要纠偏吗？

**Comment by SmallChi** [comment]
设备上报的是wgs84坐标系，根据自己使用的地图运营商去做相应的转换。

**Comment by 491134648** [comment]
大兄弟，谢谢！

**Comment by wgms** [comment]
为什么没有一个微信群？

**Comment by wgms** [comment]
> 这种坐标中国境内要纠偏吗？

取决于你地图的坐标系，这个应该是标准的WGS84坐标系，你如果用百度地图就要转成百度地图的坐标系坐标，如果要用高德就要转成高德的坐标系。
