### ISSUE TITLE
如何持续不断的从服务端接收数据？

### ISSUE THREAD

**Issue by 327** [SmallChi/JT808#17]
感谢您提供的封装实现，目前用来向服务端发送数据效果很好。
但是目前没有看到在哪里处理来自服务端的消息？主要是两个需求：
1、需要根据服务端回复确认消息是否发送成功，是否需要重传
2、服务端会主动推送一些指令给客户端，比如远程控车这种指令，这就需要客户端持续不断的监听Socket去读取数据。

请问以上两点，在您的项目里是如何实现的，特别是第二点。

**Comment by hnfjj** [comment]
你微信号发我发自我的华为手机-------- 原始邮件 --------发件人： 王强 <notifications@github.com>日期： 2020年8月27日周四 20:17收件人： SmallChi/JT808 <JT808@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [SmallChi/JT808] 如何持续不断的从服务端接收数据？ (#17)
感谢您提供的封装实现，目前用来向服务端发送数据效果很好。
但是目前没有看到在哪里处理来自服务端的消息？主要是两个需求：
1、需要根据服务端回复确认消息是否发送成功，是否需要重传
2、服务端会主动推送一些指令给客户端，比如远程控车这种指令，这就需要客户端持续不断的监听Socket去读取数据。
请问以上两点，在您的项目里是如何实现的，特别是第二点。
