### ISSUE TITLE
获取轨迹数据的需要适配哪个消息？

### ISSUE THREAD

**Issue by tmljob** [SmallChi/JT808#29]
请教个问题哈
服务端要获取轨迹数据的话，是适配位置信息汇报【0200】，还是定位数据批量上报【0704】？还是需要同时适配处理？这两种消息上报上来位置数据有什么差别？ @SmallChi

**Comment by SmallChi** [comment]
同时需要适配，0200是处理实时，在网络不好的情况下，0200是不管用的，这时候是需要0704进行补传，0704也是包含补传和实时数据。

**Comment by tmljob** [comment]
> 同时需要适配，0200是处理实时，在网络不好的情况下，0200是不管用的，这时候是需要0704进行补传，0704也是包含补传和实时数据。

好的，感谢回复~,
我们只适配了0200所以轨迹显示总有问题，后面把0704 补传的也加上看下。
