### ISSUE TITLE
请问有无兼容Framework4.6.2的版本呢

### ISSUE THREAD

**Issue by zhangboyanzhangboyan** [SmallChi/JT808#30]
我需要在Unity端使用此SDK

编译为NET462时,应该是System.Text.Encoding.CodePages版本太高不行

然后我又将System.Text.Encoding.CodePages版本降低到了4.6.0

使用net462编译依然不过

**Comment by zhangboyanzhangboyan** [comment]
我需要将Nuget包降级到2.2.0才能正常编译使用,但这个版本没有对应文档和bug修复情况...

**Comment by SmallChi** [comment]
@zhangboyanzhangboyan 预览版已发布最新JT808.2.6.2-preview4兼容netstandard2.0，可以试试。
