### ISSUE TITLE
messageid not found

### ISSUE THREAD

**Issue by ankushgowda2026** [SmallChi/JT808#38]
serializer.Serialize(JT808MsgId._0x1205.CreateCustomMsgId2019(Client?.DeviceCode, new JT808_0x1205()

'JT808MsgId' does not contain a definition for '_0x1205'

**Comment by yedajiang44** [comment]
给一个复现的单元测试

**Comment by yedajiang44** [comment]
Can you give a reproducible unit test? @ankushgowda2026

**Comment by ankushgowda2026** [comment]
request = serializer.Serialize((JT808MsgId._0x1205).CreateCustomMsgId2019(Client?.DeviceCode, new JT808_0x1205()
                    {
                        AlarmFlag=1,
                        AVResourceType=2,
                        BeginTime=Convert.ToDateTime("2024-08-08 10:20:01"),
                        EndTime=Convert.ToDateTime("2024-08-08 10:50:01"),
                        FileSize=3,
                        LogicChannelNo=(byte)channel,
                        MemoryType=5,
                        StreamType=6
                        
                    }));
                    
                    Hi @yedajiang44 i am trying to upload the video from the perticular device

**Comment by ankushgowda2026** [comment]
Thank you, @yedajiang44 I am able to resolve the problem using packets, but I have a small doubt. Where do I need to point (ftpserver or cms server)? If I point to any server, I am not passing any port or IP, so how can I reseave the files?

**Comment by yedajiang44** [comment]
This is a query, when the server sends 0x9205, you just need to return 0x1205. When the server sends 0x9206, then send the relevant resources to ftp.
