### ISSUE TITLE
大佬，这次更新吐血了呀。

### ISSUE THREAD

**Issue by AchaInChina** [SmallChi/JT808#4]
大神，你这次更新，我准备合并版本发现合不上了。看了一下修改，真的是从新出发了。

**Comment by SmallChi** [comment]
是啊，新版的主要是为了模块化，可以更好的兼容设备消息协议冲突，相对序列化器也更容易读懂一点，性能也提升了一点。

**Comment by AchaInChina** [comment]
哦了，手动同步一波！
