### ISSUE TITLE
mutimediaupload

### ISSUE THREAD

**Issue by ankushgowda2026** [SmallChi/JT808#40]
Hi, I need to upload the images from the DVR so I am able to achieve (jT808_0X0801.MultimediaType == 0x00). This is by manually enabling the snapshot and setting the interval of the snapshot in the device, but I need to enable the snapshot and set the settings through  the jt808. May I know how to do it?

**Comment by yedajiang44** [comment]
send 0x8103

```c#
var package = new JT808Package
{
    Header = new JT808Header
    {

    },
    Bodies = new JT808_0x8103
    {
        ParamList = [
            new JT808_0x8103_0x0064 {
                ParamValue = 10//This value is four bytes. Please see the documentation for detailed settings.
            }
        ]
    }
};
```
