### ISSUE TITLE
2019版本JT808_0x0107解析制造商有误

### ISSUE THREAD

**Issue by vla** [SmallChi/JT808#43]
原始数据

7E010740660100000000010941000493000700FF3838383838434B31303043000000000000000000000000000000000000000000000000313030303439330000000000000000000000000000000000000000000000898603249475600329000748572D56322E350E434B313030432D4A542D5630323402209B7E

制造商ID(MakerId)看源码读取11个字节，实际2019是5个字节，在线JTTools解析错误！

**Comment by SmallChi** [comment]
这个0x0107制造商ID跟0x0100里面的制造商ID不是一个东西吗？

**Comment by vla** [comment]
我测试了好几个2019设备以及查阅部标协议，都是5个字节。不太清楚你这里为什么是11个字节

**Comment by vla** [comment]
> 这个0x0107制造商ID跟0x0100里面的制造商ID不是一个东西吗？

对啊，因为我调试已经注册过了，所以没上报0x0100，你不说我也没发现！

**Comment by SmallChi** [comment]
我看了，所以要是部标上报的都是5个字节，这两天抽时间改下，之前是一厢情愿了。

**Comment by SmallChi** [comment]
这两天跟新版工具一起上线。
